### ISSUE TITLE
Update sidebar for `apply_to_file` now `apply_to_text_file`, etc.

### ISSUE THREAD

**Issue by etienned** [getnikola/nikola-site#15]
A sidebar in the Handbook page show how to use `apply_to_file` function. This function was replace by two new functions: `apply_to_text_file` and `apply_to_binary_file`. Docs should reflect this change.

**Comment by Kwpolska** [comment]
Fixed in getnikola/nikola, will appear on the website on next release.  Thanks!

In the future, please file issues against [getnikola/nikola](/getnikola/nikola), that’s where all the documentation is stored and written.
