### ISSUE TITLE
2015 Summer Redesign: Content plan

### ISSUE THREAD

**Issue by da2x** [getnikola/nikola-site#20]
- [x]  Front page
  - [x] ~~Three–five~~Six highlights
- [ ] Features
  - [x] Sexy icons and short paragraphs
  - [ ] Sexy videos
- [x] Download
  - [x] Install with pip
  - [x] Quick start
  - [x] Install from source package
  - [x] Install from git / other
  - [x] License
- [x] Documentation
  - [x] Quick start ~~(more detailed)~~ _one is enough_
  - [x] Handbook
  - [x] WordPress import (?)
  - [x] Mailing list / IRC (logs, search fields!) _(link from support superpage)_
  - [x] ~~Developer resources -> Development page~~ _what would be on it?_
- [ ] Featured sites
  - [ ] Some static info sites
  - [ ] Some blogs
  - [ ] Text “…and your next project?” at the bottom
- [x] Add-ons
  - [x] Themes
  - [x] Plug-ins
- [x] Development
  - [x] License
  - [x] Bugs
  - [x] Source
  - [x] Themeing and plug-ins _(in Documentation menu)_

License and quickstart are indeed duplicated.

**Comment by Kwpolska** [comment]
Do so many people care about licenses we need to give it that much care?  Or will just a short “MIT license” be enough?

**Comment by Aeyoun** [comment]
Developers must know before contributing anything, and new prospecting users should know what they’re getting into (most don’t care, no). But we should not be off putting to new users wondering “what’s the license on this thing?”. So sticking it at the bottom on the for-every-new-users-page (the download and quick-start page) seems appropriate. Project who hide their license are often either  proprietary or  has weird licenses. So I had that in the back of my mind too.

A short MIT License with link to full license is okay. We just need to acknowledge it these key places.

**Comment by Kwpolska** [comment]
Most of this is done, closing.
