### ISSUE TITLE
Add Mac install instructions

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola-site#24]
1. Install [Xcode](https://itunes.apple.com/app/xcode/id497799835) from the App Store (free – but requires Apple ID login)
1.  `easy_install --user --upgrade --always-copy nikola[extras]`
1. `echo 'export PATH="~/Library/Python/2.7/bin:$PATH"' > ~/.bash_profile`
1. `source ~/.bash_profile`

Should work for OS X 10.9–10.11. Will be a per-user installation as system-wide installations will require the user to either read off spell after spell from a book of dark magic or break their system.

Will work regardless of Python distribution (Apple, Homebrew, MacPorts).

**Comment by Kwpolska** [comment]
No pip?

-- 
Chris Warrick <https://chriswarrick.com>

**Comment by Aeyoun** [comment]
No, it’s not available by default. Instructions can be changed to make it available if that is preferable.

1. Install [Xcode](https://itunes.apple.com/app/xcode/id497799835) from the App Store (free – but requires Apple ID login)
1.  `easy_install --user --upgrade --always-copy pip`
1. `echo 'export PATH="~/Library/Python/2.7/bin:$PATH"' > ~/.bash_profile`
1. `source ~/.bash_profile`
1. `pip install --user nikola[extras]`

**Comment by Kwpolska** [comment]
Okay, I'll throw it into the redesign on Monday.

-- 
Chris Warrick <https://chriswarrick.com>
Sent from my Galaxy S3.
18 lip 2015 13:29 "Daniel Aleksandersen" <notifications@github.com>
napisał(a):

**Comment by Kwpolska** [comment]
Can I direct users at Homebrew, and use `virtualenv` for the install? Is the following okay?

(Homebrew requires xcode and pulls in [pip and wheel](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/python.rb))

> ##### With [Homebrew](http://brew.sh/) (recommended)
> If you have Homebrew installed, skip the first step. If you have Python installed from Homebrew, skip the second step.
>
> 1. Install [Homebrew](http://brew.sh/).
> 2. Run `brew install python`
> 3. Install virtualenv with `pip install virtualenv`
> 4. Follow the instructions on the right.
>
> ##### Standalone
>
> You can skip steps 3 and 4 if you use ~/Library/Python/2.7/bin/virtualenv as your virtualenv command.
>
> 1. Install [Xcode](#too-lazy-to-link) (free) from the App Store.
> 2. Install pip and virtualenv with `easy_install --user --upgrade --always-copy pip wheel virtualenv`
> 3. Update your $PATH with `echo 'export PATH="~/Library/Python/2.7/bin:$PATH"' >> ~/.bash_profile`
> 4. Reload your profile with `source ~/.bash_profile`
> 5. Follow the instructions on the right.

**Comment by jfcaron3** [comment]
Unfortunately the popular "package managers" on OSX kind of conflict with each other.  MacPorts, Homebrew, and Fink each recommend to avoid using any of the other ones.  This means that OSX users who already use one of those systems are locked-in.  It would be good to provide instructions for each system, or at least for MacPorts /and/ Homebrew which account for most users.

**Comment by Aeyoun** [comment]
The original instructions avoid all of this by installing it in isolation separately from whatever all of these managers do.

**Comment by Kwpolska** [comment]
I left in the standalone instructions.

@jfcaron3, looks okay?

> ##### With [MacPorts](https://www.macports.org/)
> 1. Install [MacPorts](https://www.macports.org/).
> 2. Install pip with `port install py-pip` 
> 3. Install virtualenv with `port install py-virtualenv`
> 4. Follow the instructions on the right.
>
> ##### With [Fink](http://www.finkproject.org/)
> 1. Install [Fink](http://www.finkproject.org/)
> 2. Install pip and virtualenv with `fink install pip-py27 virtualenv-py27`
> 3. Follow instructions on the right.
