### ISSUE TITLE
Repeated note on https://getnikola.com/extending.html

### ISSUE THREAD

**Issue by jjconti** [getnikola/nikola-site#27]
The note "If you want to publish your plugin on the Plugin Index, read the docs for the Index (and the .plugin file examples and explanations)." appears twice in https://getnikola.com/extending.html

**Comment by Kwpolska** [comment]
three times* even

**Comment by Kwpolska** [comment]
I don’t think we should count this as a bug, people might not read the entire document and thus break things.
