### ISSUE TITLE
Something broke in the site's menu

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola-site#32]
May be a Nikola bug, don't know. If you check the documentation menu it shows ``<strong>`` instead of **being strong**.

**Comment by Kwpolska** [comment]
Global bug.

All the HTML escaping added recently is at fault. Some of it (in visible
places, that is) should be reverted.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Aeyoun** [comment]
Well, is it a bug when someone creates a tag called `<html>`? It’s not really defined whether the  author should escape things like this manually or if Nikola will do it for him. I have to blog posts who’s title include html tags that I want escaped.

**Comment by ralsina** [comment]
In the `<title>` tag they need to be escaped, but also in the `<h1>` tag? And also in the navigation menu?

**Comment by Aeyoun** [comment]
Or should author's be expected to provide escaped titles when they want to use them? It's better to be consistent everywhere, I think. Note that this also would mean that `Quoted "titles"` would have to be escaped, and I'm afraid that could be a common usecase.

Many CMSes just escape everything and don't let users include raw HTML tags to adjust styling. Where does it stop? Do we allow iframe in titles? What about feeds?

**Comment by Kwpolska** [comment]
> Quoted "titles"

Since when is `<h1>Hello, "world!"</h1>` bad?

We are not “many CMSes”.  We are written with people who understand HTML in mind.

IMO we should allow people to have anything they like and not have them play with weird CSS.

**Comment by Aeyoun** [comment]
> Since when is `<h1>Hello, "world!"</h1>` bad?

Since forever? `<meta content="Hello, "World!"">`

    '&"<>`

**Comment by Kwpolska** [comment]
We can leave `<h1>` unescaped and escape it inside attributes…

**Comment by ralsina** [comment]
So, we need to escape in templates according to context. Life is hard.

**Comment by Aeyoun** [comment]
Then you're inconsistent. Inconsistency will probably confuse everyone.

**Comment by Kwpolska** [comment]
I believe most people will understand why this was done.
