### ISSUE TITLE
License explanation is a copyleft license explanation, but Nikola is under MIT license?

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola-site#36]
Excerpted from handbook License section:

> If you are not familiar with free software licensing: In general, you should be able to do pretty much anything you want, unless you modify Nikola. If you modify it, and share it with someone else, that someone else should get all your modifications under the same license you got it.

I feel this is a bit strange: this explanation is closer to a copyleft license, but far from MIT license. Maybe we should change the text?

**Comment by Kwpolska** [comment]
Do you have a better explanation?

**Comment by Kwpolska** [comment]
The only thing that is missing is the “don’t hold liable” cause (written in ALL CAPS). Everything else seems to be okay. What other improvements would you make, though?

**Comment by xuhdev** [comment]
> ... If you modify it, and share it with someone else, that someone else should get all your modifications under the same license you got it.

I don't think this is true... under MIT license, distributing the software with the same license is not enforced.

**Comment by Kwpolska** [comment]
This is sort-of like it:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Please provide a full explanation example that you think is correct.

**Comment by xuhdev** [comment]
How about the following

> If you are not familiar with free software licensing, here is a brief explanation for you (Note this is not a legal advice). In general, you should be able to do pretty much anything you want, including modifying Nikola, using and redistributing the original version or the your modified version. However, if you redistribute Nikola to someone else, either the modified version or the original version, the copyright notice in the `LICENSE.txt` file must be included in your distribution. For details you can read `LICENSE.txt`.

**Comment by Kwpolska** [comment]
Sounds good. I’ll change it to that (with a little bit of copy-editing).

**Comment by Kwpolska** [comment]
Done.
