### ISSUE TITLE
Short codes examples in the handbook are broken

### ISSUE THREAD

**Issue by haakenlid** [getnikola/nikola-site#37]
**Screenshot:** https://getnikola.com/handbook.html#using-a-shortcode
![image](https://cloud.githubusercontent.com/assets/1686266/13226486/f4194cd0-d991-11e5-8c4d-542c210a8296.png)

**input:** https://github.com/getnikola/nikola-site/blob/master/stories/manual.txt#L822
```
Example of a paired shortcode (note that we don't have a highlight shortcode yet ;-)::

    {{% highlight python %}} A bunch of code here {{% /highlight %}}
```

**output:** 
```
<p>Example of a paired shortcode (note that we don't have a highlight shortcode yet ;-):</p>
<pre class="literal-block">

</pre>
```

**Comment by ralsina** [comment]
Thanks for the report, I will fix it ASAP

**Comment by ralsina** [comment]
Fixed.

**Comment by haakenlid** [comment]
That was quick :trophy:

**Comment by Kwpolska** [comment]
@ralsina that the handbook seems to have reST/shortcode errors in it, mind checking that?
